inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/**/*
    - bin/**/*
    - Guardfile

Style/Documentation:
  Enabled: false

LineLength:
  Enabled: false

BlockLength:
  Exclude:
    - spec/**/*

MixinUsage:
  Exclude:
    - spec/**/*
